### ISSUE TITLE
[Pi4] 2020-09-13-netbsd-raspi-aarch64.img.gz local PEBCAK or...?

### ISSUE THREAD

**Issue by drawkula** [ebijun/NetBSD#128]
I got it from http://cdn.netbsd.org/pub/NetBSD/misc/jun/raspberry-pi/2020-09-13-aarch64 and the MDsum was correct, then wrote it to SD 2 times (a) using Gnome's disk tool (restore image (uncompressed before)) and (b) directly `zcat`ed it to `/dev/sdc` on a Thinkpad.  Both times neither the Debian10 notebook, nor the Pi4 (new a few days ago) accepted the FAT partition as correct.

Am I overlooking something?

**Comment by ebijun** [comment]
Image file has GPT partition.take a look as GPT with such as gdisk on debian.
> netbsd# vnconfig vnd0 2020-09-13-netbsd-raspi-aarch64.img
netbsd# dkctl vnd0 listwedges
/dev/rvnd0: 2 wedges:
dk0: EFI, 1b3840 blocks at 3, type: msdos
dk1: netbsd-root, 4751355 blocks at 163843, type: ffs
netbsd# mount_msdos /dev/dk0 /mnt
netbsd# ls /mnt
EFI                 bcm2711-rpi-4-b.dtb netbsd.img
RPI_EFI.fd          config.txt          overlays
Readme.md           fixup4.dat          start4.elf

**Comment by drawkula** [comment]
After booting RaspiOS-Lite once for looking at the EEPROM version (which was shown as uptodate) it now boots NetBSD.
Did RaspiOS silently change something?
Well, at least it did increase my confusion.

I just see the "login:" after the 1st boot due to root-FS resizing.

Thanks for your patience!
