### ISSUE TITLE
RPi4 aarch64 image rcorder scripts with no providers

### ISSUE THREAD

**Issue by lpvm** [ebijun/NetBSD#130]
Hi,

I copied the image of the 16th of January and booted it.
When booting, it shows that several `/etc/rc.d/` scripts have no providers.
Please see the attached image.

![netbsd_rpi4](https://user-images.githubusercontent.com/7320067/107403261-d1da9c80-6afc-11eb-9685-58939ca8ea68.jpg)

**Comment by ebijun** [comment]
Thanx for report.I can't see rcorder error message during update RPI aarch64 image,
http://mail-index.netbsd.org/port-arm/2021/02/18/msg007182.html

**Comment by lpvm** [comment]
I didn't install this new image and corrected the issue for the old in my installation.
Thank you.
