### ISSUE TITLE
Barebones image

### ISSUE THREAD

**Issue by DavidVentura** [ebijun/NetBSD#58]
Hi
I've built a barebones image of NetBSD 7 but I can't partition my disk properly.
If I follow this: https://wiki.netbsd.org/tutorials/how_to_install_netbsd_on_hpcarm/ my partition table dies somewhere in there. Even if it doesn't die while running these steps, it is dead when I shut down the virtual machine.

Could you make a <512MB image (I only need a tty to start) or guide me through the partitioning process? I have the release ready

**Comment by ebijun** [comment]
I make < 512MB image on
ftp://ftp.netbsd.org/pub/NetBSD/misc/jun/hpcarm/2015-10-27-netbsd-hpcarm-bare.img.gz .
with https://github.com/ebijun/NetBSD/blob/master/hpcarm/Image/Makefile.bare
hpcarm boot fails on NetBSD7 but -current works fine.

**Comment by DavidVentura** [comment]
Thanks a lot! While this boots, it gives me a corrupt fs and mounts / read only. I will investigate further tomorrow

**Comment by ebijun** [comment]
make smaller(or bigger) image if requested.
